/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.amit.SparkSpring;

import org.apache.spark.sql.Dataset;
import org.apache.spark.sql.Row;
import org.apache.spark.sql.SparkSession;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class Library {
	@Autowired
	SparkConf sparkConf;

	public boolean someLibraryMethod() {
	SparkSession sparkSession=sparkConf.getSparkSession();
   // Dataset<Row> df= sparkSession.read().option("header","true").option("inferSchema","true").csv("C:\\Users\\amitabhat\\Downloads\\Projects\\TROW\\source\\inputfiles\\source.csv");
  // df.show();
		return true;
	}

}
